export const LOAD_BOOKS = 'LOAD_BOOKS'
export const SET_LOADING = 'SET_LOADING'
export const LOAD_IMAGES = 'LOAD_IMAGES'
export const SHOW_MODAL = 'SHOW_MODAL'
export const SET_SUCCESS = 'SET_SUCCESS'
export const SET_ERROR = 'SET_ERROR'
export const ON_SEARCH = 'ON_SEARCH'
export const MOBILE_SEARCH = 'MOBILE_SEARCH'
